# Install command-line tools using Homebrew
# Usage: `brew bundle Brewfile`

# Make sure we'e using the latest Homebrew
update

# Upgrade any already-installed formulae
upgrade

# Install GNU core utilities (those that come with OS X are outdated)
# Don't forget to add `$(brew --prefix coreutils)/libexec/gnubin` to `$PATH`.
install coreutils
#sudo ln -s /usr/local/bin/gsha256sum /usr/local/bin/sha256sum

# Install some other useful utilities like `sponge`
install moreutils
# Install GNU `find`, `locate`, `updatedb`, and `xargs`, `g`-prefixed
install findutils
# Install GNU `sed`, overwriting the built-in `sed`
install gnu-sed --default-names
# Install Bash 4
# Note: don't forget to add `/usr/local/bin/bash` to `/etc/shells` before running `chsh`.
install bash
install bash-completion

# Install wget with IRI support
install wget --enable-iri

# Install more recent versions of some OS X tools
install vim --override-system-vi
install homebrew/dupes/grep
install homebrew/dupes/screen

# Install some CTF tools; see https://github.com/ctfs/write-ups
install binutils
install nmap

# Install other useful binaries
install pv
install tree
install dos2unix
install mackup
install openssl
install readline

# Shell
install zsh
install zsh-completions
install autojump
install terminal-notifier

# Dev
install git
install gradle
install mariadb
install subversion

# Remove outdated versions from the cellar
cleanup
