#!/bin/bash

if test ! $(which brew); then
  echo "Installing homebrew..."
  ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
fi

source ./Brewfile
source ./Caskfile

sudo echo "/usr/local/bin/zsh" >> /etc/shells
sudo echo "/usr/local/bin/bash" >> /etc/shells

