#!/bin/bash

if test ! $(which brew); then
  echo "Installing homebrew..."
  ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
fi

echo "Now run brew installs:"
echo "  ./Brewfile"
echo "  ./Caskfile"
echo ""
echo "Once done add zsh to shells:"
echo "  sudo sh -c \"echo /usr/local/bin/zsh >> /etc/shells\""
echo ""
echo "Then install oh-my-zsh:"
echo "  curl -L http://install.ohmyz.sh | sh"
echo ""
echo "Finally load configuration with Mackup (assuming you're using it)"
echo "  mackup restore"
