#!/bin/bash
# Install command-line tools using Homebrew
# Usage: `brew bundle Brewfile`

# Make sure we'e using the latest Homebrew
brew update

# Upgrade any already-installed formulae
brew upgrade

# Install GNU core utilities (those that come with OS X are outdated)
# Don't forget to add `$(brew --prefix coreutils)/libexec/gnubin` to `$PATH`.
brew install coreutils

# Install some other useful utilities like `sponge`
brew install moreutils
# Install GNU `find`, `locate`, `updatedb`, and `xargs`, `g`-prefixed
brew install findutils
# Install GNU `sed`, overwriting the built-in `sed`
brew install gnu-sed --default-names
# Install Bash 4
# Note: don't forget to add `/usr/local/bin/bash` to `/etc/shells` before running `chsh`.
brew install bash
brew install bash-completion

# Install wget with IRI support
brew install wget --enable-iri

# Install more recent versions of some OS X tools
brew install vim --override-system-vi
brew install homebrew/dupes/grep
brew install homebrew/dupes/screen

# Install some CTF tools; see https://github.com/ctfs/write-ups
brew install binutils
brew install nmap

# Install other useful binaries
brew install pv
brew install tree
brew install dos2unix
brew install mackup
brew install openssl
brew install readline
brew install corkscrew

# Shell
brew install zsh
brew install zsh-completions
brew install autojump
brew install terminal-notifier

# Dev
brew install git
brew install gradle
brew install mariadb
brew install subversion

# Remove outdated versions from the cellar
brew cleanup
