#!/bin/bash
# Install native apps
# Usage: `brew bundle Caskfile`

brew install caskroom/cask/brew-cask
brew tap caskroom/versions
brew tap caskroom/fonts

brew cask install alfred
brew cask install java
brew cask install java6
brew cask install java7
brew cask install font-sauce-code-powerline
brew cask install dropbox
brew cask install google-chrome
brew cask install iterm2
brew cask install the-unarchiver
brew cask install transmission
brew cask install virtualbox
brew cask install vlc
brew cask install vagrant
brew cask install spotify
brew cask install mailbox
brew cask install skype
brew cask install quicklook-json
brew cask install sourcetree
brew cask install intellij-idea

brew cask alfred link
